### ISSUE TITLE
First line of file parsing

### ISSUE THREAD

**Issue by derikb** [technosophos/LibRIS#1]
I'm using LibRIS to parse citations (thanks, it's saved me tons of time), and I found what I think is a bug. When parsing files, the first line of the file is not being parsed correctly. As far as I can tell the first line of the file fails to match the regex in the parser, causing that line to be left out of the parsed data. Since, in RIS, this is the Publication Type, it's an important one.

What I can't figure out is why that line is problematic. Maybe you can?

**Comment by derikb** [comment]
Also, if I add a blank line to the front of the file being I upload and parse it, everything works fine.

**Comment by technosophos** [comment]
Mind sending me a piece of sample data? I'll try to replicate here, but a sample might speed it up.

**Comment by derikb** [comment]
Sure, thing. On it's way presently.

**Comment by technosophos** [comment]
The culprit appears to be a Unicode BOM at the beginning of the file. I should be able to strip it out before parsing begins.

**Comment by technosophos** [comment]
derikb: Thanks for the suggested fix. I have checked in the code. Let me know if you see any further problems.
